# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir builds
        GOOS=windows GOARCH=amd64 go build -v -o builds/sshterm.exe ./sshterm/sshterm.go
        GOOS=windows GOARCH=i386 go build -v -o builds/sshterm32.exe ./sshterm/sshterm.go

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sshterm build
        path: builds
